[build]
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"

[[headers]]
  # Header ini berlaku untuk akses ke API/fungsi kamu
  for = "/.netlify/functions/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
